export const fakeGames = [
         {
            id: 1,
            name: "juego 1",
            description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque, aspernatur?",
            exercise: 2,
            module: 1,
            status: true,
         },
         {
            id: 2,
            name: "juego 2",
            description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque, aspernatur?",
            exercise: 1,
            module: 1,
            status: false,
         },
         {
            id: 3,
            name: "juego 3",
            description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque, aspernatur?",
            exercise: 6,
            module: 1,
            status: true,
         },
         {
            id: 4,
            name: "juego 1",
            description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque, aspernatur?",
            exercise: 3,
            module: 2,
            status: false,
         },
         {
            id: 5,
            name: "juego 1",
            description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque, aspernatur?",
            exercise: 3,
            module: 3,
            status: false,
         },
         {
            id: 6,
            name: "juego 2",
            description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque, aspernatur?",
            exercise: 2,
            module: 3,
            status: false,
         }
]